#pragma once

#define WINDOW_WIDTH 990
#define WINDOW_HEIGHT 900
#define MAP_HEIGHT 100
#define MAP_WIDTH 100
#define ACTOR_NUM 5
#define HALLSNUM 15
#define ROOMSNUM 10
#define MINROOMLEN 3
#define MAXROOMLEN 25
#define BGCOLOR 0
#define PLAYERCOLOR BGCOLOR | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define AICOLOR BGCOLOR | FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY
#define DEFAULTCOLOR BGCOLOR | FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_GREEN
enum terrain_t {EMPTY=' ', WALL='#'/*0xB1*/};
enum map_t {RANDOM, HALLWAYS, ROOMS};
enum aistate_t { PLAYER, READY, SEARCHING };